// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM1USuxTPqLzcQVSfcoaERuK_bCo_HAWc',
    appId: '1:143956678385:web:322044da6d35e610da7b50',
    messagingSenderId: '143956678385',
    projectId: 'fir-app-23a8c',
    authDomain: 'fir-app-23a8c.firebaseapp.com',
    storageBucket: 'fir-app-23a8c.appspot.com',
    measurementId: 'G-DHKTNTENC2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbTvhrO_-pBZsC5F8F12XZnkw7VDrrI1M',
    appId: '1:143956678385:android:aacb33254813102cda7b50',
    messagingSenderId: '143956678385',
    projectId: 'fir-app-23a8c',
    storageBucket: 'fir-app-23a8c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZobaL7WRf80fNiLfcSHd8XIJ0d_8tkH0',
    appId: '1:143956678385:ios:581c76474d89b55bda7b50',
    messagingSenderId: '143956678385',
    projectId: 'fir-app-23a8c',
    storageBucket: 'fir-app-23a8c.appspot.com',
    iosBundleId: 'com.example.firebaseNoteapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZobaL7WRf80fNiLfcSHd8XIJ0d_8tkH0',
    appId: '1:143956678385:ios:a829694e29c1a852da7b50',
    messagingSenderId: '143956678385',
    projectId: 'fir-app-23a8c',
    storageBucket: 'fir-app-23a8c.appspot.com',
    iosBundleId: 'com.example.firebaseNoteapp.RunnerTests',
  );
}
